name: open_meteo
description: "Modern Weather App - Aplikasi cuaca dengan desain modern dan mewah"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  geolocator: 14.0.2
  geocoding: ^2.1.1
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.8
  clipboard: ^0.1.3
  provider: ^6.1.1
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  rename_app: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.4

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Light.ttf
          weight: 300

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/icon.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

  # Android adaptive (disarankan)
 # adaptive_icon_foreground: "assets/icon/icon_fg.png"
 # adaptive_icon_background: "#FFFFFF"
 # adaptive_icon_monochrome: "assets/icon/icon_mono.png"

  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 256

  macos:
    generate: true
    image_path: "assets/icon/icon.png"
